apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: event-listener
  labels:
    app: eventListener
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eventListener
  template:
    metadata:
      labels:
        app: eventListener
    spec:
      containers:
      - name: eventlistener
        image: shanepeckham/rabbitmqlistenerack:v8
        ports:
        - containerPort: 8080
        env:
        - name: TEAMNAME
          value: "team1-LDS"
        - name: RABBITMQHOST
          value: "amqp://user:4pQDaeKoo7@queenly-frog-rabbitmq.default.svc.cluster.local:5672"
        - name: PARTITIONKEY
          value: "0"
        - name: PROCESSENDPOINT
          value: http://fullfillorder-deployment.default.svc.cluster.local:8080/v1/order


