apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: fullfillorder-deployment
  labels:
    app: fullfillOrder
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fullfillOrder
  template:
    metadata:
      labels:
        app: fullfillOrder
    spec:
      containers:
      - name: fullfillorder
        image: shanepeckham/fulfillorderack:v8
        volumeMounts:
        - mountPath: /order
          name: order-volume
        ports:
        - containerPort: 8080
        env:
        - name: MONGOHOST
          valueFrom:
            secretKeyRef:
              name: db-conn
              key: db-conn.txt
        - name: TEAMNAME
          value: "team1_LDS"
      volumes:
      - name: order-volume
        emptyDir: {}          


