apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: fullfillorder-deployment
  labels:
    app: fullfillOrder
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fullfillOrder
  template:
    metadata:
      labels:
        app: fullfillOrder
    spec:
      containers:
      - name: fullfillorder
        image: shanepeckham/fulfillorderack:v7
        volumeMounts:
        - mountPath: /order
          name: order-volume
        ports:
        - containerPort: 8080
        env:
        - name: MONGOHOST
          value: "mongodb://mongodb-mongodb.default.svc.cluster.local"
        - name: TEAMNAME
          value: "team1_LDS"
      volumes:
      - name: order-volume
        persistentVolumeClaim:
          claimName: prodpvceastus
