apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: captureorder-deployment
  labels:
    app: captureOrder
spec:
  replicas: 1
  selector:
    matchLabels:
      app: captureOrder
  template:
    metadata:
      labels:
        app: captureOrder
    spec:
      containers:
      - name: captureorder
        image: shanepeckham/captureorderack:v8
        ports:
        - containerPort: 8080
        env:
        - name: MONGOHOST
          valueFrom:
            secretKeyRef:
              name: db-conn
              key: db-conn.txt
        - name: TEAMNAME
          value: team1-LDS
        - name: EVENTPOLICYKEY
          value: "piJrWysVVHVAaO02TJUPjaIVUP8fQhICN9exqGmKfFU="
        - name: EVENTPOLICYNAME
          value: eventhub-dev-policy
        - name: EVENTURL
          value: "https://eventhub-dev.servicebus.windows.net/eventhub-dev"
