apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: event-listener
  labels:
    app: eventListener
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eventListener
  template:
    metadata:
      labels:
        app: eventListener
    spec:
      containers:
      - name: eventlistener
        image: shanepeckham/eventhublistenerack:v8
        ports:
        - containerPort: 8080
        env:
        - name: TEAMNAME
          value: "team1-LDS"
        - name: PARTITIONKEY
          value: "1"
        - name: PROCESSENDPOINT
          value: http://fullfillservice.default.svc.cluster.local:8080/v1/order
        - name: EVENTHUBPATH
          value: "eventhub-prod"
        - name: EVENTHUBCONNSTRING
          value: "Endpoint=sb://eventhub-prod.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=a9MrOFcPobEWuIT2GYqBQL3pZXP1dlzRbYdXj+GJpSk="
