apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: event-listener
  labels:
    app: eventListener
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eventListener
  template:
    metadata:
      labels:
        app: eventListener
    spec:
      containers:
      - name: eventlistener
        image: shanepeckham/eventhublistenerack:v8
        ports:
        - containerPort: 8080
        env:
        - name: TEAMNAME
          value: "team1-LDS"
        - name: PARTITIONKEY
          value: "0"
        - name: PROCESSENDPOINT
          value: http://fullfillservice.default.svc.cluster.local:8080/v1/order
        - name: EVENTHUBPATH
          value: [eventhubname]
        - name: EVENTHUBCONNSTRING
          value: "Endpoint=sb://[youreventhub].servicebus.windows.net/;SharedAccessKeyName=[keyname];SharedAccessKey=[key]"
